package Operaciones;


/**
* Operaciones/_IOperacionesStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Practica.idl
* Sunday, October 20, 2019 7:34:16 PM CDT
*/

public class _IOperacionesStub extends org.omg.CORBA.portable.ObjectImpl implements Operaciones.IOperaciones
{

  public boolean registrar (Operaciones.Usuario Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrar", true);
                Operaciones.UsuarioHelper.write ($out, Ops);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrar (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // registrar

  public boolean iniciarsesion (Operaciones.Usuario Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("iniciarsesion", true);
                Operaciones.UsuarioHelper.write ($out, Ops);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return iniciarsesion (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // iniciarsesion

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Operaciones/IOperaciones:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _IOperacionesStub
