package Operaciones;


/**
* Operaciones/IOperacionesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Practica.idl
* Sunday, October 20, 2019 7:34:16 PM CDT
*/

abstract public class IOperacionesHelper
{
  private static String  _id = "IDL:Operaciones/IOperaciones:1.0";

  public static void insert (org.omg.CORBA.Any a, Operaciones.IOperaciones that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Operaciones.IOperaciones extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Operaciones.IOperacionesHelper.id (), "IOperaciones");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Operaciones.IOperaciones read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IOperacionesStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Operaciones.IOperaciones value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Operaciones.IOperaciones narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Operaciones.IOperaciones)
      return (Operaciones.IOperaciones)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Operaciones._IOperacionesStub stub = new Operaciones._IOperacionesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Operaciones.IOperaciones unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Operaciones.IOperaciones)
      return (Operaciones.IOperaciones)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Operaciones._IOperacionesStub stub = new Operaciones._IOperacionesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
