package Operaciones;

/**
* Operaciones/IOperacionesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Practica.idl
* Sunday, October 20, 2019 7:34:16 PM CDT
*/

public final class IOperacionesHolder implements org.omg.CORBA.portable.Streamable
{
  public Operaciones.IOperaciones value = null;

  public IOperacionesHolder ()
  {
  }

  public IOperacionesHolder (Operaciones.IOperaciones initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Operaciones.IOperacionesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Operaciones.IOperacionesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Operaciones.IOperacionesHelper.type ();
  }

}
