package Operaciones;


/**
* Operaciones/IOperacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Practica.idl
* Sunday, October 20, 2019 7:34:16 PM CDT
*/

public interface IOperacionesOperations 
{
  boolean registrar (Operaciones.Usuario Ops);
  boolean iniciarsesion (Operaciones.Usuario Ops);
} // interface IOperacionesOperations
