package Operaciones;


/**
* Operaciones/IOperaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Practica.idl
* Sunday, October 20, 2019 7:34:16 PM CDT
*/

public interface IOperaciones extends IOperacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IOperaciones
