package Operaciones;


/**
* Operaciones/UsuarioHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Practica.idl
* Sunday, October 20, 2019 7:34:16 PM CDT
*/

abstract public class UsuarioHelper
{
  private static String  _id = "IDL:Operaciones/Usuario:1.0";

  public static void insert (org.omg.CORBA.Any a, Operaciones.Usuario that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Operaciones.Usuario extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "nombre",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "contra",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Operaciones.UsuarioHelper.id (), "Usuario", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Operaciones.Usuario read (org.omg.CORBA.portable.InputStream istream)
  {
    Operaciones.Usuario value = new Operaciones.Usuario ();
    value.nombre = istream.read_string ();
    value.contra = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Operaciones.Usuario value)
  {
    ostream.write_string (value.nombre);
    ostream.write_string (value.contra);
  }

}
