package Operaciones;

/**
* Operaciones/UsuarioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Practica.idl
* Sunday, October 20, 2019 7:34:16 PM CDT
*/

public final class UsuarioHolder implements org.omg.CORBA.portable.Streamable
{
  public Operaciones.Usuario value = null;

  public UsuarioHolder ()
  {
  }

  public UsuarioHolder (Operaciones.Usuario initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Operaciones.UsuarioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Operaciones.UsuarioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Operaciones.UsuarioHelper.type ();
  }

}
