package Operaciones;


/**
* Operaciones/Usuario.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Practica.idl
* Sunday, October 20, 2019 7:34:16 PM CDT
*/

public final class Usuario implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public String contra = null;

  public Usuario ()
  {
  } // ctor

  public Usuario (String _nombre, String _contra)
  {
    nombre = _nombre;
    contra = _contra;
  } // ctor

} // class Usuario
